name: release
on:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'alpha'
      - 'canary-*'
  pull_request: {}

# Cancel any previous run (see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build-storybook
      # semantic-release skips not configured branches(see: release.config.js) or pull-requests
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
